databases:
  - name: datalog-postgres
    databaseName: datalog_db
    user: datalog_user
    plan: free  # or 'starter' for production

services:
  - type: web
    name: datalog-backend
    runtime: python
    plan: free  # or 'starter' for production
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: datalog-postgres
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
